# Generated by Django 2.2.5 on 2023-03-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialMaster',
            fields=[
                ('materialID', models.AutoField(primary_key=True, serialize=False)),
                ('materialName', models.CharField(max_length=150)),
                ('specifications', models.CharField(max_length=150)),
                ('minimum_quantity', models.IntegerField()),
                ('category', models.CharField(choices=[('category1', 'Product'), ('category2', 'Service'), ('category3', 'Tools')], max_length=50)),
                ('unit', models.CharField(choices=[('unit1', 'Kg'), ('unit2', 'Liter'), ('unit3', 'Pcs'), ('unit4', 'Feet'), ('unit5', 'Inch')], max_length=50)),
            ],
        ),
    ]
